
use std::collections::HashMap;
use std::sync::OnceLock;

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum TokenKind {
    Identifier,
    String,
    Number,

    // Punctuation / Operators
    LParen,
    RParen,
    LBrace,
    RBrace,
    LBracket,
    RBracket,
    Or,
    And,
    Tilde,
    Ampersand,
    Comma,
    Dot,
    SemiColon,
    Colon,
    Plus,
    Minus,
    Star,
    Slash,
    Percent,
    Caret,
    Question,
    QuestionQuestion,
    Geq,
    Gt,
    FatArrow,
    TripleEq,
    DoubleEq,
    Eq,
    Leq,
    Lt,
    ColonGt,
    ColonGtGt,
    ColonEq,
    ColonColon,
    ColonColonGt,
    DotQuestion,
    DotDot,
    Arrow,
    StarStar,
    Dollar,
    Hash,
    NotEq,
    NotDoubleEq,
    
    // KERML Keywords
    Assoc,
    Behavior,
    Bool,
    Chains,
    Class,
    Classifier,
    Composite,
    Conjugate,
    Conjugates,
    Conjugation,
    Connector,
    Const,
    Datatype,
    Differences,
    Disjoining,
    Disjoint,
    Expr,
    Feature,
    Featured,
    Featuring,
    Function,
    Interaction,
    Intersects,
    Inv,
    Inverse,
    Inverting,
    Member,
    Metaclass,
    Multiplicity,
    Namespace,
    Portion,
    Predicate,
    Redefinition,
    Specialization,
    Step,
    Struct,
    Subclassifier,
    Subset,
    Subtype,
    Type,
    Typed,
    Typing,
    Unions,
    Var,

    // SysML Keywords
    About,
    Abstract,
    Accept,
    Action,
    Actor,
    After,
    Alias,
    All,
    Allocate,
    Allocation,
    Analysis,
    // And,
    As,
    Assert,
    Assign,
    Assume,
    At,
    Attribute,
    Bind,
    Binding,
    By,
    Calc,
    Case,
    Comment,
    Concern,
    Connect,
    Connection,
    Constant,
    Constraint,
    Crosses,
    Decide,
    Def,
    Default,
    Defined,
    Dependency,
    Derived,
    Do,
    Doc,
    Else,
    End,
    Entry,
    Enum,
    Event,
    Exhibit,
    Exit,
    Expose,
    False,
    Filter,
    First,
    Flow,
    For,
    Fork,
    Frame,
    From,
    Hastype,
    If,
    Implies,
    Import,
    In,
    Include,
    Individual,
    Inout,
    Interface,
    Istype,
    Item,
    Join,
    Language,
    Library,
    Locale,
    Loop,
    Merge,
    Message,
    Meta,
    Metadata,
    Nonunique,
    Not,
    Null,
    Objective,
    Occurrence,
    Of,
    // Or,
    Ordered,
    Out,
    Package,
    Parallel,
    Part,
    Perform,
    Port,
    Private,
    Protected,
    Public,
    Redefines,
    Ref,
    References,
    Render,
    Rendering,
    Rep,
    Require,
    Requirement,
    Return,
    Satisfy,
    Send,
    Snapshot,
    Specializes,
    Stakeholder,
    Standard,
    State,
    Subject,
    Subsets,
    Succession,
    Terminate,
    Then,
    Timeslice,
    To,
    Transition,
    True,
    Until,
    Use,
    Variant,
    Variation,
    Verification,
    Verify,
    Via,
    View,
    Viewpoint,
    When,
    While,
    Xor,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub struct Span {
    pub start: usize,
    pub end: usize,
    pub line: usize,
    pub column: usize,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Token {
    pub kind: TokenKind,
    pub lexeme: String,
    pub span: Span,
}

const KEYWORD_TOKENS: &[(&str, TokenKind)] = &[
    ("assoc", TokenKind::Assoc),
    ("behavior", TokenKind::Behavior),
    ("bool", TokenKind::Bool),
    ("chains", TokenKind::Chains),
    ("class", TokenKind::Class),
    ("classifier", TokenKind::Classifier),
    ("composite", TokenKind::Composite),
    ("conjugate", TokenKind::Conjugate),
    ("conjugates", TokenKind::Conjugates),
    ("conjugation", TokenKind::Conjugation),
    ("connector", TokenKind::Connector),
    ("const", TokenKind::Const),
    ("datatype", TokenKind::Datatype),
    ("differences", TokenKind::Differences),
    ("disjoining", TokenKind::Disjoining),
    ("disjoint", TokenKind::Disjoint),
    ("expr", TokenKind::Expr),
    ("feature", TokenKind::Feature),
    ("featured", TokenKind::Featured),
    ("featuring", TokenKind::Featuring),
    ("function", TokenKind::Function),
    ("interaction", TokenKind::Interaction),
    ("intersects", TokenKind::Intersects),
    ("inv", TokenKind::Inv),
    ("inverse", TokenKind::Inverse),
    ("inverting", TokenKind::Inverting),
    ("member", TokenKind::Member),
    ("metaclass", TokenKind::Metaclass),
    ("multiplicity", TokenKind::Multiplicity),
    ("namespace", TokenKind::Namespace),
    ("portion", TokenKind::Portion),
    ("predicate", TokenKind::Predicate),
    ("redefinition", TokenKind::Redefinition),
    ("specialization", TokenKind::Specialization),
    ("step", TokenKind::Step),
    ("struct", TokenKind::Struct),
    ("subclassifier", TokenKind::Subclassifier),
    ("subset", TokenKind::Subset),
    ("subtype", TokenKind::Subtype),
    ("type", TokenKind::Type),
    ("typed", TokenKind::Typed),
    ("typing", TokenKind::Typing),
    ("unions", TokenKind::Unions),
    ("var", TokenKind::Var),
    ("about", TokenKind::About),
    ("abstract", TokenKind::Abstract),
    ("accept", TokenKind::Accept),
    ("action", TokenKind::Action),
    ("actor", TokenKind::Actor),
    ("after", TokenKind::After),
    ("alias", TokenKind::Alias),
    ("all", TokenKind::All),
    ("allocate", TokenKind::Allocate),
    ("allocation", TokenKind::Allocation),
    ("analysis", TokenKind::Analysis),
    ("and", TokenKind::And),
    ("as", TokenKind::As),
    ("assert", TokenKind::Assert),
    ("assign", TokenKind::Assign),
    ("assume", TokenKind::Assume),
    ("at", TokenKind::At),
    ("attribute", TokenKind::Attribute),
    ("bind", TokenKind::Bind),
    ("binding", TokenKind::Binding),
    ("by", TokenKind::By),
    ("calc", TokenKind::Calc),
    ("case", TokenKind::Case),
    ("comment", TokenKind::Comment),
    ("concern", TokenKind::Concern),
    ("connect", TokenKind::Connect),
    ("connection", TokenKind::Connection),
    ("constant", TokenKind::Constant),
    ("constraint", TokenKind::Constraint),
    ("crosses", TokenKind::Crosses),
    ("decide", TokenKind::Decide),
    ("def", TokenKind::Def),
    ("default", TokenKind::Default),
    ("defined", TokenKind::Defined),
    ("dependency", TokenKind::Dependency),
    ("derived", TokenKind::Derived),
    ("do", TokenKind::Do),
    ("doc", TokenKind::Doc),
    ("else", TokenKind::Else),
    ("end", TokenKind::End),
    ("entry", TokenKind::Entry),
    ("enum", TokenKind::Enum),
    ("event", TokenKind::Event),
    ("exhibit", TokenKind::Exhibit),
    ("exit", TokenKind::Exit),
    ("expose", TokenKind::Expose),
    ("false", TokenKind::False),
    ("filter", TokenKind::Filter),
    ("first", TokenKind::First),
    ("flow", TokenKind::Flow),
    ("for", TokenKind::For),
    ("fork", TokenKind::Fork),
    ("frame", TokenKind::Frame),
    ("from", TokenKind::From),
    ("hastype", TokenKind::Hastype),
    ("if", TokenKind::If),
    ("implies", TokenKind::Implies),
    ("import", TokenKind::Import),
    ("in", TokenKind::In),
    ("include", TokenKind::Include),
    ("individual", TokenKind::Individual),
    ("inout", TokenKind::Inout),
    ("interface", TokenKind::Interface),
    ("istype", TokenKind::Istype),
    ("item", TokenKind::Item),
    ("join", TokenKind::Join),
    ("language", TokenKind::Language),
    ("library", TokenKind::Library),
    ("locale", TokenKind::Locale),
    ("loop", TokenKind::Loop),
    ("merge", TokenKind::Merge),
    ("message", TokenKind::Message),
    ("meta", TokenKind::Meta),
    ("metadata", TokenKind::Metadata),
    ("nonunique", TokenKind::Nonunique),
    ("not", TokenKind::Not),
    ("null", TokenKind::Null),
    ("objective", TokenKind::Objective),
    ("occurrence", TokenKind::Occurrence),
    ("of", TokenKind::Of),
    ("or", TokenKind::Or),
    ("ordered", TokenKind::Ordered),
    ("out", TokenKind::Out),
    ("package", TokenKind::Package),
    ("parallel", TokenKind::Parallel),
    ("part", TokenKind::Part),
    ("perform", TokenKind::Perform),
    ("port", TokenKind::Port),
    ("private", TokenKind::Private),
    ("protected", TokenKind::Protected),
    ("public", TokenKind::Public),
    ("redefines", TokenKind::Redefines),
    ("ref", TokenKind::Ref),
    ("references", TokenKind::References),
    ("render", TokenKind::Render),
    ("rendering", TokenKind::Rendering),
    ("rep", TokenKind::Rep),
    ("require", TokenKind::Require),
    ("requirement", TokenKind::Requirement),
    ("return", TokenKind::Return),
    ("satisfy", TokenKind::Satisfy),
    ("send", TokenKind::Send),
    ("snapshot", TokenKind::Snapshot),
    ("specializes", TokenKind::Specializes),
    ("stakeholder", TokenKind::Stakeholder),
    ("standard", TokenKind::Standard),
    ("state", TokenKind::State),
    ("subject", TokenKind::Subject),
    ("subsets", TokenKind::Subsets),
    ("succession", TokenKind::Succession),
    ("terminate", TokenKind::Terminate),
    ("then", TokenKind::Then),
    ("timeslice", TokenKind::Timeslice),
    ("to", TokenKind::To),
    ("transition", TokenKind::Transition),
    ("true", TokenKind::True),
    ("until", TokenKind::Until),
    ("use", TokenKind::Use),
    ("variant", TokenKind::Variant),
    ("variation", TokenKind::Variation),
    ("verification", TokenKind::Verification),
    ("verify", TokenKind::Verify),
    ("via", TokenKind::Via),
    ("view", TokenKind::View),
    ("viewpoint", TokenKind::Viewpoint),
    ("when", TokenKind::When),
    ("while", TokenKind::While),
    ("xor", TokenKind::Xor),
];

const SYMBOL_TOKENS: &[(&str, TokenKind)] = &[
    ("(", TokenKind::LParen),
    (")", TokenKind::RParen),
    ("{", TokenKind::LBrace),
    ("}", TokenKind::RBrace),
    ("[", TokenKind::LBracket),
    ("]", TokenKind::RBracket),
    ("~", TokenKind::Tilde),
    ("&", TokenKind::Ampersand),
    (",", TokenKind::Comma),
    (".", TokenKind::Dot),
    (";", TokenKind::SemiColon),
    (":", TokenKind::Colon),
    ("+", TokenKind::Plus),
    ("-", TokenKind::Minus),
    ("*", TokenKind::Star),
    ("/", TokenKind::Slash),
    ("%", TokenKind::Percent),
    ("^", TokenKind::Caret),
    ("?", TokenKind::Question),
    ("??", TokenKind::QuestionQuestion),
    (">=", TokenKind::Geq),
    (">", TokenKind::Gt),
    ("=>", TokenKind::FatArrow),
    ("===", TokenKind::TripleEq),
    ("==", TokenKind::DoubleEq),
    ("=", TokenKind::Eq),
    ("<=", TokenKind::Leq),
    ("<", TokenKind::Lt),
    (":>", TokenKind::ColonGt),
    (":>>", TokenKind::ColonGtGt),
    (":=", TokenKind::ColonEq),
    ("::", TokenKind::ColonColon),
    ("::>", TokenKind::ColonColonGt),
    (".?", TokenKind::DotQuestion),
    ("..", TokenKind::DotDot),
    ("->", TokenKind::Arrow),
    ("**", TokenKind::StarStar),
    ("$", TokenKind::Dollar),
    ("#", TokenKind::Hash),
    ("!=", TokenKind::NotEq),
    ("!==", TokenKind::NotDoubleEq),
];

static KEYWORD_LOOKUP: OnceLock<HashMap<&'static str, TokenKind>> = OnceLock::new();
static SYMBOL_LOOKUP: OnceLock<HashMap<&'static str, TokenKind>> = OnceLock::new();

impl TokenKind {
    pub fn from_keyword(value: &str) -> Option<Self> {
        KEYWORD_LOOKUP
            .get_or_init(|| KEYWORD_TOKENS.iter().copied().collect())
            .get(value)
            .copied()
    }

    pub fn from_symbol(value: &str) -> Option<Self> {
        SYMBOL_LOOKUP
            .get_or_init(|| SYMBOL_TOKENS.iter().copied().collect())
            .get(value)
            .copied()
    }
}